server: 
  port: 4024
  servlet:
    context-path: /app

spring: 
  application:
    name: todolist-redis
  cache:
    type: redis
  redis:
     sentinel:
       master: master1
       nodes:
        - 10.0.30.101:26379
        - 10.0.30.102:26379
     cluster:       
       nodes:
        - 10.0.30.101:6379
        - 10.0.30.102:6379  
       maxRedirects: 2